version: '2'

services:
   db:
     image: mariadb:latest
     volumes:
       - ./db/mariadb:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: changeme 
       MYSQL_DATABASE: flaskapi 
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbpass

   flask:
     depends_on:
       - db
     image: rorski/angular2-randomuser-backend:v0.5
     ports:
       - "8000:80"
     environment:
       - PYTHONPATH=/opt/flask
     # Wrapper script to check connectivity to DB, populate and run supervisord
     command: ["/root/run-supervisord.sh"]
     restart: always
